### ISSUE TITLE
希望兼容参数出现同名的情况

### ISSUE THREAD

**Issue by hold-baby** [reeli/ts-codegen#5]
```json
"parameters": [
    {
      "name": "id",
      "in": "path",
      "description": "",
      "required": true,
      "type": "string"
    },
    {
      "name": "id",
      "in": "query",
      "description": "",
      "required": true,
      "type": "string"
    },
]
```
这种在生成入参的时候会报错，但理论上两个不是同一个东西确实是可以同名的

**Comment by reeli** [comment]
@hold-baby 

在 3.3.3 版本中已修复。如果 path param 和 query param 有冲突，会给 path param 增加一个 `inPath` 的后缀。结果如下：

```ts
export const getId = createRequest<
  {
    id: string;
    idInPath: string;
  },
  Resource
>("getId", ({ idInPath, id }) => ({
  url: `/api/v2/test/${idInPath}`,
  method: "get",
  params: {
    id,
  },
}));

```

**Comment by reeli** [comment]
> ```json
> "parameters": [
>     {
>       "name": "id",
>       "in": "path",
>       "description": "",
>       "required": true,
>       "type": "string"
>     },
>     {
>       "name": "id",
>       "in": "query",
>       "description": "",
>       "required": true,
>       "type": "string"
>     },
> ]
> ```
> 
> 这种在生成入参的时候会报错，但理论上两个不是同一个东西确实是可以同名的



> ```json
> "parameters": [
>     {
>       "name": "id",
>       "in": "path",
>       "description": "",
>       "required": true,
>       "type": "string"
>     },
>     {
>       "name": "id",
>       "in": "query",
>       "description": "",
>       "required": true,
>       "type": "string"
>     },
> ]
> ```
> 
> 这种在生成入参的时候会报错，但理论上两个不是同一个东西确实是可以同名的

在 3.3.3 版本中已修复。如果 path param 和 query param 有冲突，会给 path param 增加一个 `inPath` 的后缀。结果如下：

```ts
export const getId = createRequest<
  {
    id: string;
    idInPath: string;
  },
  IResource
>("getId", ({ idInPath, id }) => ({
  url: `/api/v2/test/${idInPath}`,
  method: "get",
  params: {
    id,
  },
}));

```

**Comment by hold-baby** [comment]
nice
