### ISSUE TITLE
期望有选项能够控制入参声明与返回值声明的生成

### ISSUE THREAD

**Issue by hold-baby** [reeli/ts-codegen#6]
希望能够导入声明避免又手动去写

![image](https://user-images.githubusercontent.com/21041219/206672318-32ec6e14-5f79-484a-8f21-3b25d39ef9dd.png)

**Comment by reeli** [comment]
> 希望能够导入声明避免又手动去写
> 
> ![image](https://user-images.githubusercontent.com/21041219/206672318-32ec6e14-5f79-484a-8f21-3b25d39ef9dd.png)

有两种方法可以解决这个问题：
1. 在 swagger 中使用 reference 来定义 response，这样 response 的类型就会被单独生成。可以参考这里： https://github.com/reeli/ts-codegen-examples/blob/master/data/swagger.json#L761
2. 对 createRequest 方法进行改造，通过 `TResp`  属性将 response 的类型绑定到请求方法上，这样外部就能够通过 `typeof getV1ConfigFileUrl.TResp` 获取到 Response 类型
```ts
import { AxiosRequestConfig } from "axios";

export const createRequestConfig = <TReq, TResp = any>(
  _: string,
  requestConfigCreator: (args: TReq) => AxiosRequestConfig,
) => {
  const fn = (args: TReq) => {
    return requestConfigCreator(args);
  };

  return Object.assign(fn, {
    TReq: {} as TReq,
    TResp: {} as TResp,
  });
};
```

**Comment by hold-baby** [comment]
nice
